server:
  port: 8085

spring:
  application:
    name: pagoservicios-favoritos
  config:
        import: optional:configserver:http://localhost:8888
  data:
      mongodb:
        host: 127.0.0.1
        port: 27017
        database: favoritos