server:
  port: 8888
  
spring:
  application:
    name: bootcamp-pagoservicios-configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/FelipeAyalaT/bootcamp-pagoservicios-configserver
          default-label: master
  profiles:
    active: dev
          