apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      role: keycloak
  template:
    metadata:
      labels:
        role: keycloak
    spec:
      containers:
      - name: keycloak
        image: felipeayala/retointegrador_keycloak
        ports:
        - containerPort: 8080
        env:
          - name: KEYCLOAK_USER
            valueFrom:
              configMapKeyRef:
                name: retointegrador-configmap
                key: keycloak_user
          - name: KEYCLOAK_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: retointegrador-configmap
                key: keycloak_password

---

apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    role: keycloak
