CREATE DATABASE IF NOT EXISTS BDPAGOSERVICIOS CHARACTER SET latin1 COLLATE latin1_swedish_ci;

USE BDPAGOSERVICIOS;

SET foreign_key_checks = 0;

DROP TABLE IF EXISTS canal;
DROP TABLE IF EXISTS servicios;
DROP TABLE IF EXISTS pagos;

SET foreign_key_checks = 1;

CREATE TABLE canal(
	CodCanal VARCHAR(2) NOT NULL,
	Name VARCHAR(250) NOT NULL,
	Status VARCHAR(10) NOT NULL,
	PRIMARY KEY (`CodCanal`)
) ENGINE=INNODB;

CREATE TABLE servicios(
   	Id INT(4) NOT NULL AUTO_INCREMENT,
	Name VARCHAR(250) NOT NULL,
    CodCanal VARCHAR(2) NOT NULL,
    Status VARCHAR(10) NOT NULL,
    PRIMARY KEY (`Id`)
) ENGINE=INNODB;

CREATE TABLE pagos(
   	Id INT(4) NOT NULL AUTO_INCREMENT,
	Suministro VARCHAR(50) NOT NULL,
    Monto DOUBLE NULL,
    ServicioId INT(4) NOT NULL,
    Username VARCHAR(150) NOT NULL,
	Fecha DATETIME NOT NULL,
    PRIMARY KEY (`Id`)
) ENGINE=INNODB;

ALTER TABLE BDPAGOSERVICIOS.servicios CONVERT TO CHARACTER SET utf8;